services:
  importer:
    container_name: ${CONTAINER:-n4o-graph-importer}
    image: ${IMPORTER_IMAGE:-ghcr.io/nfdi4objects/n4o-graph-importer:main}
    volumes:
      - ${STAGE:-./stage}:/app/stage
      - ${DATA:-./data}:/app/data:ro

    # Everything below is only for local development and testing of the image.
    # Please don't copy to your local docker-compose.yml!
    build:
      context: .
      dockerfile: Dockerfile
