services:
  fuseki:
    image: ${FUSEKI_IMAGE:-ghcr.io/nfdi4objects/n4o-fuseki:main}
    ports:
      - "3030:3030"
    networks:
      - n4o
    restart: always
    healthcheck:
      #test: ["CMD", "wget", "--post-data", "query=DESCRIBE <>", "http://localhost:3030/n4o", "-O", "/dev/null"]
      test: ["CMD", "echo"]
      # requires Docker >= 25.0.0
      start_interval: 1s
      start_period: 5s    # directly check on startup
      interval: 5s       # then check every 5 seconds
 
  apis:
    image: ${APIS_IMAGE:-ghcr.io/nfdi4objects/n4o-graph-apis:main}
    ports:
      - ${PORT:-8000}:8000
    volumes:
      - ./config-apis.yml:/app/config.yaml:ro
      - ${STAGE:-./stage}:/app/stage:ro
    networks:
      - n4o
    depends_on:
      fuseki: 
        condition: service_healthy

  converter:
    image: ghcr.io/nfdi4objects/lido-rdf-converter:main
    networks:
      - n4o

networks:
  n4o:
    driver: bridge
