#!/usr/bin/bash

. utils.sh

set -euo pipefail
function error() { echo $@ >&2; exit 1; }

if [[ $# -ne 2 ]]; then
    echo "Usage: $0 DOI|URL directory"
    echo "Download Data from Zenodo publication, given by DOI"
    exit
fi

id=$1
if [[ "$id" =~ ^https://zenodo\.org/records/[0-9]+$ ]]; then
  id="${id##*/}"
elif [[ "$id" =~ ^https://doi\.org/10\.5281/zenodo\.[0-9]+$ ]]; then
  id="${id##*.}"
else
  error "Expecting Zenodo DOI or record URL"
fi

dir=$2
[[ -d "$dir" ]] || error "Directory not found: $dir"

doi=https://doi.org/10.5281/zenodo.$id

cd $dir

# TODO: Zenodo does not have last-modified header
url="https://zenodo.org/api/records/$id/files-archive"
echo "Downloading $doi from $url"
wget -nv -O files-archive.zip $url

# TODO: Get DCAT-AP (RDF) or DataCite format
curl -s https://zenodo.org/api/records/$id | jq . > zenodo-metadata.json
curl -s https://zenodo.org/records/$id/export/dcat-ap > zenodo-metadata.rdf

# TODO: generate datapackage
# fido -zip files-archive -nomatchprintf "" -matchprintf "%(info.filesize)s,%(info.mimetype)s,%(info.filename)s\n"
