#!/usr/bin/bash
. utils.sh

if [ $# -ne 2 ]; then
    echo "Usage: $0 <graph> <file>"
    echo "Load an RDF Turtle file into a triple store via SPARQL Graph Store HTTP protocol. An existing graph is overridden."
    exit 1
fi

graph=$1
file=$2

[[ -e "$file" ]] || error "Missing $file"

echo "Loading $file into graph $graph"
curl --fail-with-body --silent -X PUT "$SPARQL_STORE" --header "Content-Type: text/turtle" \
    --url-query "graph=$graph" \
    --upload-file "$file"
