#!/usr/bin/bash
. utils.sh

echo -n "Loading N4O Terminologies Metadata into the Knowledge Graph"
./load-rdf-graph https://graph.nfdi4objects.net/terminology/ stage/terminology/terminologies.ttl || error "FAILED"
echo OK
