#!/usr/bin/bash
. utils.sh

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 COLLECTION_ID|all"
    echo "Load collection data and metadata of a collection from stage into triple store"
    exit
fi

function load_collection() {
    collection=$1
    [[ "$collection" =~ ^[0-9]*$ ]] || error "Collection ID must be numeric!"
    uri=https://graph.nfdi4objects.net/collection/$collection

    rdf=$STAGE/collection/$collection/filtered.nt
    about=$STAGE/collection/$collection/collection.json

    [[ -e "$rdf" ]] || error "Missing $rdf"
    [[ -e "$about" ]] || error "Missing $about"

    ./load-collection-metadata $collection
    ./load-rdf-graph $uri $rdf
}

if [[ "$1" = "all" ]]; then
    for collection in $STAGE/collection/*; do
        load_collection $(basename $collection)
    done
else
    load_collection $1
fi
