#!/usr/bin/bash
set -euo pipefail

function usage() {
    echo "Usage: $0 COLLECTION_ID"
    echo "Update description about a collection in triple store."
    exit
}

[[ "${1:-}" =~ ^[0-9]*$ ]] || usage

function error() {
    echo $@ >&2
    exit 1
}

id=$1
uri=https://graph.nfdi4objects.net/collection/$id

collection=stage/collection/$id/collection.nt
[[ -s "$collection" ]] || error "Missing or empty $collection"

issued=$(date -Iminutes)

# check whether API is available
./sparql-update "INSERT DATA {}" || error "SPARQL Update endpoint not available!"

echo "Deleting metadata of $uri"
sparql=$(cat <<-SPARQL
PREFIX n4oc: <https://graph.nfdi4objects.net/collection/>
PREFIX dct: <http://purl.org/dc/terms/>
WITH n4oc:
DELETE { ?s ?p ?o }
WHERE {
  { VALUES ?s { n4oc:$id } ?s ?p ?o }
  UNION
  { VALUES ?o { n4oc:$id } ?s ?p ?o } 
}
SPARQL
)

./sparql-update "$sparql"
    
echo "Adding new metadata of $uri"
sparql=$(cat <<-SPARQL
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
INSERT DATA { GRAPH <https://graph.nfdi4objects.net/collection/> {
$(< $collection)
<$uri> dct:issued "$issued"^^xsd:dateTime .
} }
SPARQL
)

#echo "$sparql"
./sparql-update "$sparql"

