#!/usr/bin/bash
# Load collection data and metadata of a collection from stage into triple store

. utils.sh
require_collection_id "$@"

rdf=$STAGE/collection/$id/filtered.nt
about=$STAGE/collection/$id/collection.json

[[ -e "$rdf" ]] || error "Missing $rdf"
[[ -e "$about" ]] || error "Missing $about"

./load-collection-metadata $id
./load-rdf-graph $uri $rdf

#if [[ "$1" = "all" ]]; then
#    for collection in $STAGE/collection/*; do
#        load_collection $(basename $id)
#    done
#else
#    load_collection $1
#fi
