#!/usr/bin/bash
# Update description about a collection in triple store

. utils.sh
require_collection_id "$@"

collection=$STAGE/collection/$id/collection.nt
[[ -s "$collection" ]] || error "Missing or empty $collection"

issued=$(date -Iminutes)

# check whether API is available
./sparql-update "INSERT DATA {}" || error "SPARQL Update endpoint not available: $SPARQL_UPDATE"

echo "Deleting metadata of $uri"
sparql=$(cat <<-SPARQL
PREFIX n4oc: <https://graph.nfdi4objects.net/collection/>
PREFIX dct: <http://purl.org/dc/terms/>
WITH n4oc:
DELETE { ?s ?p ?o }
WHERE {
  { VALUES ?s { n4oc:$id } ?s ?p ?o }
  UNION
  { VALUES ?o { n4oc:$id } ?s ?p ?o } 
}
SPARQL
)

./sparql-update "$sparql"
    
echo "Adding new metadata of $uri"
sparql=$(cat <<-SPARQL
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
INSERT DATA { GRAPH <https://graph.nfdi4objects.net/collection/> {
$(< $collection)
<$uri> dct:issued "$issued"^^xsd:dateTime .
} }
SPARQL
)

./sparql-update "$sparql"
