#!/usr/bin/bash
set -euo pipefail
function error() { echo $@ >&2; exit 1; }

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 COLLECTION_ID|all"
    echo "Load filtered RDF triples of a collection into the triple store"
    exit
fi

function load_collection() {
    collection=$1
    [[ "$collection" =~ ^[0-9]*$ ]] || error "Collection ID must be numeric!"
    uri=https://graph.nfdi4objects.net/collection/$collection

    rdf=stage/collection/$collection/filtered.nt
    about=stage/collection/$collection/collection.json

    [[ -e "$rdf" ]] || error "Missing $rdf"
    [[ -e "$about" ]] || error "Missing $about"

    ./load-collection-metadata $collection --issued
    ./load-rdf-graph $uri $rdf
}

if [[ "$1" = "all" ]]; then
    for collection in stage/collection/*; do
        load_collection $(basename $collection)
    done
else
    load_collection $1
fi
