#!/usr/bin/bash

. utils.sh
require_collection_id "$@"

if [[ $# -ge 2 ]]; then     # pass source URL for testing
  url=$2
else                        # get source URL from collections database
  collections=$STAGE/collection/collections.json
  [[ -f $collections ]] || error "Missing $collections, please update list of collections!"

  name=$(jq -r ".[]|select(.id==\"$uri\")|.name" $collections)
  [[ -n "$name" ]] || error "Collection $id not found!"
  echo $name

  # create collection.json and collection.nt

  stage=$STAGE/collection/$id
  about=$stage/collection.json
  mkdir -p $stage

  jq -r ".[]|select(.id==\"$uri\")" $collections > $about
  npm run --silent -- jsonld2rdf -c collection-context.json $about > $stage/collection.nt

  url=$(jq -r ".url" $about)
fi

# TODO: support OAI-PMH for LIDO/XML

echo "Receive RDF data from Repository"
./download-from-repository $url $stage
python ./unpack-zenodo.py $stage      # TODO: move to download-from-repository
/transform-rdf $stage/triples.nt     # includes validation

