#!/usr/bin/bash

. utils.sh
require_collection_id "$@"

connector=

if [[ $# -eq 3 ]]; then     # pass source and connector for testing
    url=$2
    connector=$3
    #
else                        # get source and connector from collections database
  collections=$STAGE/collection/collections.json
  [[ -f $collections ]] || error "Missing $collections, please update list of collections!"

  name=$(jq -r ".[]|select(.id==\"$uri\")|.name" $collections)
  [[ -n "$name" ]] || error "Collection $id not found!"
  echo $name

  # create collection.json and collection.nt

  stage=$STAGE/collection/$id
  about=$stage/collection.json
  mkdir -p $stage

  jq -r ".[]|select(.id==\"$uri\")" $collections > $about
  npm run --silent -- jsonld2rdf -c collection-context.json $about > $stage/collection.nt

  # get connector

  url=$(jq -r ".url" $about)
  if [[ "$url" == https://doi.org/10.5281/zenodo.* ]]; then
    connector=zenodo
  fi
fi

if [[ $connector == "zenodo" ]]; then
  echo "Receive data from Zenodo"
  ./download-zenodo $url
  error "Extacting data from Zenodo not fully implemented yet!"
else
  error "Unknown or unsupported connector $connector how to get data for the collection!"
fi

# create filtered.nt

error "Not implemented yet!"
