#!/usr/bin/bash

. utils.sh
require_collection_id "$@"

if [[ $# -eq 3 ]]; then     # pass source and connector for testing
    url=$2
    connector=$3
    #
else                        # get source and connector from collections database
 # COLLECTIONS=collections.csv
  #https://github.com/nfdi4objects/n4o-databases/blob/main/n4o-collections.csv
    error "Not implemented yet!"
fi

if [[ $connector == "zenodo" || $connector == "oaipmh" ]
    ...


# create collection.nt
# create filtered.nt

error "Not implemented yet!"
