#!/usr/bin/bash
. utils.sh

if [ $# -ne 1 ]; then
    echo "Usage: $0 SPARQL"
    echo "Execute arbitrary SPARQL Update query."
    exit 1
fi

curl --silent --fail-with-body -X POST "$SPARQL_UPDATE" --header "Content-Type: application/sparql-update" --data-binary "$1"
