#!/usr/bin/bash
. utils.sh


original=$1
stage=$(dirname $(realpath "$1"))

unique="$stage/unique.nt"
duplicated="$stage/duplicated.nt"
filtered="$stage/filtered.nt"
removed="$stage/removed.nt"

declare -A rdfformats=( ["ttl"]="turtle" ["rdf"]="rdfxml")
format="${original##*.}"
fmt="${rdfformats[$format]}"

tmp=$original.tmp    
rm -f "$tmp"
rapper -q -i $fmt  "$original" | sort -u > "$tmp"

if [[ ! -s "$tmp" ]]; then
    rm "$tmp"
    echo "$original ist syntaktisch nicht korrekt oder leer!"
    exit 1
fi

mv "$tmp" "$unique"

rapper -q -i $fmt "$original" | sort | uniq -d > "$duplicated"

# TODO: extend rdffilter for one-pass
npm run --silent -- rdffilter "$unique" -o "$filtered" --stats -f ./js/rdffilter.js
npm run --silent -- rdffilter "$unique" -o "$removed" -r -f ./js/rdffilter.js

wc -l "$duplicated"
wc -l "$removed"
wc -l "$filtered"
