#!/usr/bin/bash
. utils.sh

mkdir -p $STAGE/collection
csv=$STAGE/collection/collections.csv
json=$STAGE/collection/collections.json
ttl=$STAGE/collection/collections.ttl

# TODO: allow to configure URL with env COLLECTIONS=
url=https://github.com/nfdi4objects/n4o-databases/raw/refs/heads/main/n4o-collections.csv

echo "Updating collections from $url"
curl -L --silent --fail $url -o $csv
wc -l $csv

npm run --silent -- csv2json < $csv > $json
npm run --silent -- jsonld2rdf -c collection-context.json $json > $ttl

echo $ttl
