#!/usr/bin/bash

SPARQL=${SPARQL:-http://localhost:3030/n4o}
SPARQL_UPDATE=${SPARQL_UPDATE:-$SPARQL}

if [ $# -ne 1 ]; then
    echo "Usage: $0 SPARQL"
    echo "Execute arbitrary SPARQL Update query."
    exit 1
fi

curl --silent --fail-with-body -X POST "$SPARQL_UPDATE" --header "Content-Type: application/sparql-update" --data-binary "$1"
